### ISSUE TITLE
多模块配置国际化，只有第一个有效，其他无效。

### ISSUE THREAD

**Issue by 877209649** [netease-kit/nim-uikit-flutter#10]
`localizationsDelegates: [
            S.delegate,
            CommonUILocalizations.delegate,
            ConversationKitClient.delegate,
            ChatKitClient.delegate,
            ContactKitClient.delegate,
            TeamKitClient.delegate,
            SearchKitClient.delegate,
            ...GlobalMaterialLocalizations.delegates,
          ],`

**Comment by shine2008** [comment]
收到，下个版本修复
