### ISSUE TITLE
android 33版本问题

### ISSUE THREAD

**Issue by xiaoxiaosong123** [netease-kit/nim-uikit-flutter#14]
![image](https://user-images.githubusercontent.com/38721777/223086917-c8b61c28-0fdb-44bb-bc0b-49ceafc701e2.png)

**Comment by netease-george** [comment]
这个您可以自行在demo 的Android gradle 文件中指定compileSdkVersion，我们也会在后续版本升级

**Comment by xiaoxiaosong123** [comment]
> 这个您可以自行进行demo的Android gradle文件中指定compileSdkVersion，我们也会在后续版本升级

我尝试compileSdkVersion=33的；但是你们的插件库某些不支持的，还是运行不了；
![image](https://user-images.githubusercontent.com/38721777/223609467-dc63d954-9448-4c62-b686-4f95893256c8.png)

**Comment by netease-george** [comment]
好的，我们会尽快升级 permission_handler

**Comment by netease-george** [comment]
1.请您在yaml中依赖netease_common_ui 到 ^1.0.1
2.将nim_chatkit_ui中的permission_handler升级到 ^10.0.0
3.更新compileSdkVersion 到33

**Comment by xiaoxiaosong123** [comment]
项目成功运行起来，感谢；

但有个警告：.pub-cache/hosted/pub.dartlang.org/sqflite-2.2.5/android/src/main/java/com/tekartik/sqflite/Database.java:94: 警告: [deprecation] PackageManager中的getApplicationInfo(String,int)已过时
            final ApplicationInfo applicationInfo = context.getPackageManager().getApplicationInfo(packageName, PackageManager.GET_META_DATA);
