### ISSUE TITLE
nim_chatkit_ui 组件安卓播放语音消息有问题

### ISSUE THREAD

**Issue by fuxianwei** [netease-kit/nim-uikit-flutter#16]
nim_chatkit_ui 组件安卓播放语音消息有问题，只有第一次有声音，后续播放没声音

**Comment by netease-george** [comment]
可以将 chat_kit_message_audio_item.dart 中的 _audioPlayer.setPlayerMode(PlayerMode.lowLatency); 
修改为_audioPlayer.setPlayerMode(PlayerMode.mediaPlayer); 解决此问题，我们也会在下个版本优化此问题
