### ISSUE TITLE
请尽快升级适配flutter 3.10.1

### ISSUE THREAD

**Issue by lvyandev** [netease-kit/nim-uikit-flutter#20]
```dart
../../.pub-cache/hosted/pub.dev/nim_chatkit_ui-1.0.1/lib/view/chat_kit_message_list/chat_kit_message_list.dart:76:62: Error: The argument type 'String?' can't be assigned to the parameter type 'String' because 'String?' is nullable and 'String' isn't.
    Clipboard.setData(ClipboardData(text: message.nimMessage.content));
```

除此之外，还有很多依赖的库也请升级一下，例如`dio`等

**Comment by netease-george** [comment]
Clipboard.setData(ClipboardData(text: message.nimMessage.content)) 的问题已经解决，但完整适配3.10的需求还需要排期解决

**Comment by Wing-Li** [comment]
> Clipboard.setData(ClipboardData(text: message.nimMessage.content)) 的问题已经解决，但完整适配3.10的需求还需要排期解决

这个问题，我还是遇到了啊？

![](https://github.com/netease-kit/nim-uikit-flutter/assets/12133489/9c8dd4c1-3e14-4fb6-9ec3-da354d5ecfc2)

环境还专门写成了 ：
environment:
  sdk: '>=2.16.1 <3.0.0'

**Comment by lvyandev** [comment]
dio能升级一下吗？怎么还是4.0.6

**Comment by Lorca-R** [comment]
demo项目也无法在3.10下正常搭建：
```
Because im_demo depends on flutter_localizations from sdk which depends on intl 0.18.0, intl 0.18.0 is required.
So, because im_demo depends on intl ^0.17.0, version solving failed.
```

**Comment by netease-george** [comment]
新版本已经支持，已经发布，请更新

**Comment by lvyandev** [comment]
很多依赖库依然没有升级，与项目冲突，还是等这些依赖库升级以后再吧

**Comment by netease-george** [comment]
如果是已有项目集成，遇到依赖三方库冲突，建议您试着用一下 dependency_overrides

**Comment by lvyandev** [comment]
比如dio 4.0和5.0之间有breaking change，这样直接override不会影响吗？

**Comment by netease-george** [comment]
您可以试一下，我们dio用的很轻

**Comment by netease-george** [comment]
ChatKitClient.instance.chatUIConfig 的问题确实忽视了，您可以采用一下这种方式，也能达到一样的效果。

IMKitRouter.instance.registerRouter(
        RouterConstants.PATH_CHAT_PAGE,
            (context) => ChatPage(
          sessionId:
          IMKitRouter.getArgumentFormMap<String>(context, 'sessionId')!,
          sessionType: IMKitRouter.getArgumentFormMap<NIMSessionType>(
              context, 'sessionType')!,
          anchor:
          IMKitRouter.getArgumentFormMap<NIMMessage>(context, 'anchor'),
              chatUIConfig: ChatKitClient.instance.chatUIConfig,
        ),
      cover: true
    );

**Comment by netease-george** [comment]
我本地测试  image_gallery_saver  1.7.1 在Flutter 3.10.3上市可以运行的,如果您那边不行的话可以试下用 dependency_overrides
