### ISSUE TITLE
通过pub upgrade升级包，app运行报错 

### ISSUE THREAD

**Issue by fuxianwei** [netease-kit/nim-uikit-flutter#28]
安卓，ios运行报错
phone_state包版本号：1.0.3

错误如下：
`Running Gradle task 'assembleDebug'...
../nim_chatkit_ui/lib/view/chat_kit_message_list/item/chat_kit_message_audio_item.dart:206:35: Error: Member not found: 'phoneStateStream'.
      _phoneStateSub = PhoneState.phoneStateStream.listen((event) {
                                  ^^^^^^^^^^^^^^^^
../nim_chatkit_ui/lib/media/video.dart:62:35: Error: Member not found: 'phoneStateStream'.
      _phoneStateSub = PhoneState.phoneStateStream.listen((event) {
                                  ^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception`

**Comment by lvyandev** [comment]
请尽快修复

**Comment by netease-george** [comment]
phone_state 升级api变更，可以在外部写死 phone_state的版本号为 1.0.3，我们之后版本会更新

**Comment by netease-george** [comment]
1.1.2 版本已经修复
