### ISSUE TITLE
NimCore.instance.settingsService.getPushNoDisturbConfig()报错

### ISSUE THREAD

**Issue by Wing-Li** [netease-kit/nim-uikit-flutter#29]
调用如下方法：

~~~
var pushConfig = await NimCore.instance.settingsService.getPushNoDisturbConfig();
~~~

错误如下：

![](https://github.com/netease-kit/nim-uikit-flutter/assets/12133489/ce98e713-7126-4c63-b8b7-c8701631250d)

**Comment by netease-george** [comment]
请问您 nim_core 是什么版本，可能是nim_core 和 platform_interface 版本不匹配

**Comment by netease-george** [comment]
请升级到 最新版本试下

**Comment by Wing-Li** [comment]
好了，确实是版本不匹配。

<img width="868" alt="image" src="https://github.com/netease-kit/nim-uikit-flutter/assets/12133489/3fca7f6d-7699-49d7-b57e-cc8db0f1db81">


如果有人遇到，可以这样：

~~~
  Future<bool> getPushClose() async {
    try {
      // true: 代表关闭
      var pushConfig = await NimCore.instance.settingsService.getPushNoDisturbConfig();
      return pushConfig?.data?.enable ?? false;
    } catch (e) {
      return false;
    }
  }
~~~
